import type { Metadata } from "next";

import "./globals.css";
import NavBar from "./components/navbar";
import Footer from "./components/footer";
import CartProvider from "./components/providers";
import { ShoppingCart } from "./components/shoppingCart";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'sonner';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="min-h-screen bg-background font-sans antialiased">
          <CartProvider>
            <Toaster position="top-center" />
            <NavBar />
            <ShoppingCart/>
            {children}
            <Footer />
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
